### ISSUE TITLE
provide function to return local time?

### ISSUE THREAD

**Issue by kdwarn** [rust-syndication/diligent-date-parser#6]
Would you be interested in a pull request that adds a function that, rather than returning UTC time if no timezone information is provided, would return local time? I've started (mostly completed?) this work here: https://github.com/kdwarn/diligent-date-parser

At least one thing that is needed is to put this behind a feature gate, since it requires `chrono::Local`, and you currently explicitly disable that by turning off default features, and I assume you'd want to continue that as the default. I've not done that before but am interested in figuring it out.

**Comment by andy128k** [comment]
This crate was created to share code between `rss` and `atom_syndication` crates.

I am not sure that local time makes sense in a context of RSS and/or Atom. (e.g. RSS is created and parsed by processes which run on computers with different time zones. Anyway you need to **guess** a time zone of the author. UTC is a bit special here because internet servers with UTC are pretty common).

On the other hand, you could change your function and pass `FixedOffset` as a parameter. This would allow you to use it like `parse_date_local("2023-02-02 19:00:00", Local::now().offset())` in your code. No need to complicate code with feature gates.

**Comment by kdwarn** [comment]
That makes sense. I also found https://docs.rs/dateparser/latest/dateparser/, which handles what I'm looking for. Oh well, had fun and learned some stuff about Rust and chrono along the way!
